config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  
  resources :books do
    resources :reviews
  end
  

  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'profile' => 'static_pages#profile'
  get    'login'   => 'sessions#new'
 
  

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations'}

end

app/models/book.rb
class Book < ActiveRecord::Base
    belongs_to :user
    belongs_to :department
    has_many :reviews
    
    # Validate parameters user set to database standards 
    
    has_attached_file :avatar, :styles => { :medium => "250x350>", :thumb => "325x475" }, :default_url => "bookcover.jpg"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    
    validates :title, :cnumber, :quality, :publisher, :department_id, :price, :campus, :presence => true
    #validates_presence_of :cnumber, :message => "can't be empty"  
    validates :cnumber, :length => {:is => 3}
    validates_format_of :quality, :campus, :with => /[a-zA-Z]*/
    
    def self.human_attribute_name(attr, options = {})
        attr == :cnumber ? 'Course Number' : super
    end
    
end

app/models/department.rb
class Department < ActiveRecord::Base
    has_many :books
    
    # Confirm that user entered a department and that it is unique to the database 
    validates :name, :presence => true
    validates_uniqueness_of :name
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :book
    belongs_to :user
    
    # Confirm that user entered a comment and that it is no longer than 150 characters 
    validates :comment, :presence => true
    validates :comment, :length =>{maximum:150};

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   # existing code

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100" }, :default_url => "notlogged.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # Connfirm that a username has been entered and is unique. 
  validates_presence_of :username
  validates_uniqueness_of :username
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
    end
  end
  
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end
  
  # Get user to enter password field 
  def password_required?
    super && provider.blank?
  end
 
 
  
  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :find_book, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
    
    def index
        # Check if user has selected a department - only display books from that department 
        if !params[:department].blank? 
          @department_id = Department.find_by(name: params[:department]).id
          @books = Book.where(:department_id => @department_id).order("created_at DESC")
        # Else, show every book in the database 
        else
          @books = Book.all.order("created_at DESC")
        end
        
        # Check if a cnumber has been entered and display all books from that department and cnumber
        if params[:cnumber]; params[:department]
          @books = Book.where('cast(cnumber as text) LIKE ? and cname LIKE ?', "%#{params[:cnumber]}%", "%#{params[:department]}%")
        end
        # Check if a user name or book title is entered in the form - display books from that user or with the book title 
        if params[:username]
          @books = Book.where('user_username LIKE ? or title LIKE ?', "%#{params[:username]}%", "%#{params[:username]}%")
        end
    end
    
    
    def show
    end

    def new
        @book = current_user.books.build
        @departments = Department.all.map {|c| [c.name, c.id]}
       
    end

    def create
        @book = current_user.books.build(book_params)
        @book.department_id = params[:department_id]
        @book.user_username = current_user.username
        @book.user_email = current_user.email
        
        # Set the department that the user has selected from the department database to the book
        if @book.department_id?
            @book.cname = @book.department.name
        end
        
        if @book.save
            redirect_to root_path
        else
            render 'new'
        end
    end
    
    def edit
        @departments = Department.all.map {|c| [c.name, c.id]}
    end
    
    def update
        @book.department_id = params[:department_id] 
        if @book.update(book_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end
    
    def destroy
        @book.destroy
        redirect_to root_path
    end
    
    private
    
    # cnumber = course number; cname = department name
    def book_params
       params.require(:book).permit(:avatar, :title, :cname, :cnumber, :quality, :publisher, :campus, :price, :department_id) 
    end
    
    def find_book
        @book = Book.find(params[:id])
    end
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  # User parameters 
  def sign_up_params
    params.require(:user).permit(:avatar, :username, :email, :password, :password_confirmation)
  end
  
  # Update user account parameters 
  def account_update_params
    params.require(:user).permit(:avatar, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_book
    before_action :find_review, only: [:edit, :update, :destroy]
     before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
    
    def new
        @review = Review.new
    end
    
    # Create a new comment - set the user id to the comment to identify who said what 
    def create 
        @review = Review.new(review_params)
        @review.book_id = @book.id
        @review.user_id = current_user.id
        @review.user_username = current_user.username
        
        if @review.save
            redirect_to book_path(@book)
        else
            render 'new'
        end
    end
    
    def edit 
        
    end
    def update
        @review = Review.find(params[:id])
    end
    def update
        if @review.update(review_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end
    def destroy 
        @review.destroy
        redirect_to book_path(@book)
    end
    
    private
    
        def review_params
            params.require(:review).permit(:comment)
        end
    
        def find_book
            @book = Book.find(params[:book_id])
        end
        
        def find_review
            @review = Review.find(params[:id])
        end
end

app/views/books/_form.html.erb
<!--Book Form - Used to get user to input book parameters-->
<!--Form is used in the new.html.erb for books-->

<div class = "center jumbotron">
<%= simple_form_for @book, :html => {:multipart => true} do |f| %>
    <% if @book.errors.any? %>
    <h1>Please fix the following error(s).</h1>
    <ul>
        <% @book.errors.full_messages.each do |message| %>
        
        <li><%= message %></li>
      
        <% end %>
        
    </ul>
    <h2>Hit 'Back' to return to the previous page</h2>
    <% else %>
        <strong>Book picture</strong>
        <p></p>
        <%= f.file_field :avatar %>
        <p></p>
        <%= f.input :title, label: "Book Title" %>
        <strong>*Department name</strong>
        <p></p>
        <%= select_tag(:department_id, options_for_select(@departments), :prompt => "Select a department") %>

        <p></p>
        <%= f.input :cnumber, label: "Course Number" %>
        <%= f.input :quality, label: "Book Quality" %>
        <%= f.input :publisher, label: "Book Publisher" %>
        <%= f.input :campus, label: "SFU Campus Location" %>
        <%= f.input :price, label: "Book Price" %>
        <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
    

<% end %>

</div>        

app/views/books/_welcome.html.erb
<!-- This is the Sign up logo for users to sign up -->
<div class = "center jumbotron">
  <h1>Welcome to SFU Used Books</h1>
  <p>This app provides you with a platform for buying/selling SFU books.</p>
  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Sign up using facebook", user_omniauth_authorize_path(:facebook), class: "btn btn-lg btn-primary" %>
  <p></p>
  or <%= link_to "Sign up using Twitter", user_omniauth_authorize_path(:twitter) %>.
  
  Already a member? <%= link_to "Click here to login",   new_user_session_path %>
</div>

<!--BUYING BOOKS-->
<!--First user selects a department and then the course number field will unhide for a more detailed search-->
<h2 id = "sections"> Buying a Book? </h2>
<ul class="nav navbar-nav">
  <li class = "dropdown">
          <a href="#" class = "btn btn-primary dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Departments<span class = "caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% Department.all.each do |department| %>
                <li>
                  <%= link_to department.name, books_path(department: department.name), class:"link" %>
                </li>
                <% end %>
            </ul>
  </li>
</ul>

</br></br></br>
<% if !params[:department].blank? %>
<h1><p style="color:white;"><class="current-department"> <%= params[:department] %></p></h1>
<% end %>

<%= form_tag books_path, method: :get do %>
<%= hidden_field_tag :department, params[:department], class: 'form-control' %>

<!--Hide course number search until user has selected a department!-->
<% if !params[:department].blank? %>
<%= text_field_tag :cnumber, params[:cnumber], placeholder: 'Three Digit Course #' %>

<%= submit_tag "Search", name: nil %>
<% end %>
<% end %>

<!-------------------------------------------------------------------------------------------------------------------------------------->

<!--DISPLAY BOOKS-->
<!--If there are no books up for sale alert user with message, otherwise list books in 4 columns-->

<% if @books.count == 0 %>
  <h1><p style="color:white;">There are no books currently</p></h1>

  <%= link_to "Add Book", new_book_path, class: "btn btn-primary" %>
  </div>
  </div>
<% else %>

<h2 id = "sections"> Selling a Book? </h2>
  <%= link_to "Add Book", new_book_path, class: "btn btn-primary" %>
  <h2 id = "sections">Recently Added Books</h2>
<% end %>

  
  
</br></br>

  <div class="row">
  <% @books.each do |book| %>
    <div class = "col-md-3">
    <a href="/books/<%= book.id %>">
      <%= image_tag book.avatar.url(:medium), class: "book" %>
    </a>
    </div>

<% end %>
  </div> 

app/views/books/edit.html.erb
<!--EDIT BOOK-->
<!--Display form of parameters to let user make any changes to the book they added-->
<!--Can only edit books they have added themselves-->
<h1><p style="color:white;">Edit Book</p></h1>
<div class = "center jumbotron">

<%= simple_form_for @book, :html => {:multipart => true} do |f| %>
   <% if @book.errors.any? %>
    <h1>Please fix the following error(s).</h1>
    <ul>
        <% @book.errors.full_messages.each do |message| %>
        
        <li><%= message %></li>
      
        <% end %>
       
    </ul>
    <h2>Hit 'Back' to return to the previous page</h2>
    <% else %>
        <strong>Book picture</strong>
        <p></p>
        <%= f.file_field :avatar %>
        <p></p>
        <%= f.input :title, label: "Book Title" %>
        <strong>*Department name</strong>
        <p></p>
        <%= f.select :department_id, @departments %>

        <p></p>
        <%= f.input :cnumber, label: "Course Number" %>
        <%= f.input :quality, label: "Book Quality" %>
        <%= f.input :publisher, label: "Book Publisher" %>
        <%= f.input :campus, label: "SFU Campus Location" %>
        <%= f.input :price, label: "Book Price" %>
        <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
    

<% end %>
</div>

app/views/books/index.html.erb
<% if current_user %>
<!-- Carousel Slide Show at top of home page that displays book covers our site has offered-->
<!--------------------------------------------------------------------------------------------------------------------------------------------->

	<div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
    <h4><img class="img-responsive center-block" src="http://ecx.images-amazon.com/images/I/51VC5o7UgKL._SX405_BO1,204,203,200_.jpg" alt="UI" style="width:250px; height:350px"><span style="font-style:normal;"><br><br><br><br></span></h4>

    		<div class="carousel-caption">
          
        </div>

    </div>
    <div class="item">
      <h4><img class="img-responsive center-block" src="http://ecx.images-amazon.com/images/I/51LJZgoNz6L._SY344_BO1,204,203,200_.jpg" alt="UI" style="width:250px; height:350px"><span style="font-style:normal;"><br><br><br><br></span>

      	<div class="carousel-caption">
          
        </div>
      	
      </h4>
    </div>
    <div class="item">
      <h4><img class="img-responsive center-block" src="http://i.imgur.com/6MBGHZk.png" alt="UI" style="width:250px; height:350px"><span style="font-style:normal;"><br><br><br><br></span>

		<div class="carousel-caption">
          
        </div>

    </div>

 </h4>


  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!--------------------------------------------------------------------------------------------------------------------------------------------->

<!--BUYING BOOKS-->
<!--First user selects a department and then the course number field will unhide for a more detailed search-->
<h2 id = "sections"> Buying a Book? </h2>
<ul class="nav navbar-nav">
  <li class = "dropdown">
          <a href="#" class = "btn btn-primary dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Departments<span class = "caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% Department.all.each do |department| %>
                <li>
                  <%= link_to department.name, books_path(department: department.name), class:"link" %>
                </li>
                <% end %>
            </ul>
  </li>
</ul>

</br></br></br>
<% if !params[:department].blank? %>
<h1><p style="color:white;"><class="current-department"> <%= params[:department] %></p></h1>
<% end %>

<%= form_tag books_path, method: :get do %>
<%= hidden_field_tag :department, params[:department], class: 'form-control' %>

<!--Hide course number search until user has selected a department!-->
<% if !params[:department].blank? %>
<%= text_field_tag :cnumber, params[:cnumber], placeholder: 'Three Digit Course #' %>

<%= submit_tag "Search", name: nil %>
<% end %>
<% end %>

<!-------------------------------------------------------------------------------------------------------------------------------------->

<!--DISPLAY BOOKS-->
<!--If there are no books up for sale alert user with message, otherwise list books in 4 columns-->

<% if @books.count == 0 %>
  <h1><p style="color:white;">There are no books currently</p></h1>

  <%= link_to "Add Book", new_book_path, class: "btn btn-primary" %>
  </div>
  </div>
<% else %>

<h2 id = "sections"> Selling a Book? </h2>
  <%= link_to "Add Book", new_book_path, class: "btn btn-primary" %>
  <h2 id = "sections">Recently Added Books</h2>
<% end %>

  
  
</br></br>

  <div class="row">
  <% @books.each do |book| %>
    <div class = "col-md-3">
    <a href="/books/<%= book.id %>">
      <%= image_tag book.avatar.url(:medium), class: "book" %>
    </a>
    </div>

<% end %>
  </div> 


<% else %>
  <%= render 'welcome' %>
<% end %>

app/views/books/new.html.erb
<!--NEW BOOK-->
<!--Generate form view to get user to enter book parameters-->

<h1><p style="color:white;">New Book</p></h1>
</br>

<%= render 'form' %>

app/views/books/show.html.erb
<!--DISPLAY BOOKS-->
<!--If there are no books up for sale alert user with message, otherwise list books in 4 columns-->


<div class="row">
    
    <div class ="col-md-4">
        <%= image_tag @book.avatar.url(:thumb), class:"book-show" %>     
        <p></p>
        

 
<!--Only let users edit or delete books if they are the user that created the book--> 
        <% if user_signed_in? %>

            <% if @book.user_id == current_user.id || current_user.id == 2 %>
               
                <%= link_to "Edit", edit_book_path(@book), class: "btn btn-primary" %>
                <%= link_to "Delete", book_path(@book), class: "btn btn-primary",  method: :delete, data: { confirm: "Are you sure?" } %>
            <% end %>
        <% end %>
    </div>
    <div class ="col-md-8">
        <div class="book-info">
            
            <h3 class="book-title">Title: <%= @book.title %></h3>
            <h4 class="book-cname">Department name: <%= @book.department.name %></h4>
            <h4 class="book-cnumber">Course number: <%= @book.cnumber %></h4>
            <h4 class="book-quality">Quality: <%= @book.quality %></h4>
            <h4 class="book-publisher">Publisher: <%= @book.publisher %></h4>
            <h4 class="book-campus">SFU campus: <%= @book.campus %></h4>
            <h4 class="book-price">Price: <%= @book.price %></h4>
            ------------------------------Seller's information--------------------------
        
            <h4 class="book-username">Username: <%= @book.user_username %></h4>
            <h4 class="book-email">Email: <%= @book.user_email %></h4>
        
            <h4><a href="https://completed.herokuapp.com/books?utf8=%E2%9C%93&username=<%= @book.user_username%>">View all my books</a>
            </h4>
            
            
        </div>
    </div>
    
<!-------------------------------------------------------------------------------------------------------------------------------------->

<!-- User Comments-->
<!--Add new comments and view comments already created for that book-->

     <div class= "col-md-8">
             <p></p>
             <div class="book-info">
            <%= render @book.reviews %>
             <% if user_signed_in? %>
            <div>
                <%=link_to "Add Comment", new_book_review_path(@book), class: "btn btn-primary"  %>
            </div>
            <%end%>
            </div>
        </div>
</div>

       
    

  
     

app/views/layouts/_header.html.erb
<!-- HEADER BAR -->
<!--Embedded buttons in header bar-->
<header class="navbar navbar-inverse">
  <div class="container">
    
    <div class="navbar-header">
      
     <%= link_to "SFU USED BOOK SALES", root_path, id: "logo" %>
      
    </div>
     <div id="navbar">
       
      <% if current_user %>
      
        <ul class="nav navbar-nav pull-right">
          
      
       <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
       
         <!--User dropdown to view profile information, books they have added, logout button, or to change their settings-->
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.username %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", profile_path %></li>
              <li>
              <a href="https://completed.herokuapp.com/books?utf8=%E2%9C%93&username=<%=current_user.username%>">My Books</a>
              </li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: :delete%>
              </li>
            </ul>
          </li>
        </ul>
      <% else %>
         <ul class="nav navbar-nav pull-right">
          <%= link_to "Login",   new_user_session_path,  class: 'navbar-brand' %>
          
          
        </ul>
      <% end %>
    </div>
   <!--Search bar for book title or user name - Displays books with title entered or created by user from username entered-->
    <ul class= "nav navbar-nav search-bar pull-left">
    <%= form_tag books_path, method: :get do %>
    <%= text_field_tag :username, params[:username], placeholder: 'Username or Book Title' %>
    <%= submit_tag "Search", name: nil %>
    <% end %>
    </ul>
    
    
      
      
      
   
        
      <ul class="nav navbar-nav pull-right">
      <li><%= link_to "Home",   root_path,  class: 'navbar-brand' %>
      <%= link_to "About",   about_path,  class: 'navbar-brand' %>
      <%= link_to "Contact",   contact_path,  class: 'navbar-brand' %>
      
 
       </ul>
   
  </div>
</header>


     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>SFU USED BOOK SALES</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="navbar">
    <ul class="nav navbar-nav">
      <li class="dropdown">
      <a href="#" class = "btn btn-primary dropdown-toggle" data-toggle="dropdown">Department<b class = "caret"></b></a>
          <ul class="dropdown-menu-depart dropdown-menu pull-left">
            <% Department.all.each do |department| %>
              <li>
                  <%= link_to department.name, books_path(department: department.name), class:"link" %>
              </li>
             <% end %>
          </ul>
      </li>
    </ul>
  </div>

  <%= render 'layouts/header' %>
  
 
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
   
  <%= yield %>
   
</div>


<div class = "container">
  <%= render 'layouts/footer' %>
</div>

 

</body>

</html>

app/views/reviews/_form.html.erb
<div class = "center jumbotron">
<%= simple_form_for([@book, @book.reviews.build]) do |f|%>
   
    <% if @review.errors.any? %>
    <h1>Please fix the following error(s).</h1>
    <ul>
        <% @review.errors.full_messages.each do |message| %>
        
            <li><%= message %></li>
        <% end %>
    </ul>
    <% end %>
    <%= f.input :comment %>
    <%= f.button :submit, "Submit comment" %>
    
<% end %>
</div>

app/views/reviews/edit.html.erb
<h1><p style="color:white;">Edit Comments</p></h1>

<%= simple_form_for([@book, @review]) do |f| %>
    <%= f.input :comment %>
    <%= f.button :submit %>
<% end %>

app/views/reviews/new.html.erb
<h1><p style="color:white;">New Comments</p></h1>

<%= render 'form' %>

app/views/static_pages/about.html.erb
<% provide(:title,"ABOUT") %>
<% provide(:content, " Webapp developed by CMPT-276 students") %>
<div class = "center jumbotron">

<% provide(:name, "About") %>
<h1> 
	<%= yield (:name) %>
</h1>
<h2> 
	<%= yield (:content) %>
</h2>
__________________________________________________________________________________________________________________________________________________________________
<div id="section">
<h2>We Build Easy and Friendly Selling Platforms</h2>
<p>
Selling books in SFU Used Books, you just need to login to our system and set up an individual account. Meanwhile, we provide Facebook login as an optional way for our customers.
</p>
<p>
Each book, which is posted on our website, has detailed information such as cover-pictures, title, book quality, and publisher.   
</p>
__________________________________________________________________________________________________________________________________________________________________

<h2>We Build Convinient Searching Engines </h2>
<p>
Searching books in SFU Used Books, you just need to click department and enter a course number. We categorize all of the text books which is selling in SFU Used Book Sales in term of SFU course outline.
</p>
<p>
You can also choose to surf on SFU Used Book Sales home page to find your favorite books, if you don't have a particular demand.     
</p>
__________________________________________________________________________________________________________________________________________________________________

<h2>In Development: We Recommend popular and Good Selling Books</h2>
<p>
Based on the selling data and comments log, we provide with our recommendations to readers and public.
</p>
<p>
We update the required text book recommendation to students.     
</p>

	


</div>

app/views/static_pages/contact.html.erb
<% provide(:title,"CONTACT") %>

<div class = "center jumbotron">

<% provide(:name, "Contact") %>
<h1> 
	<%= yield (:name) %>
</h1>

<div class = "relative">
	<div class = "absolute">
		<div id = "header">
		<h2>We Are CMPT- 276 Students</h2> 
		<h4>We can be reached using the following emails:</h4>
___________________________________________________________________________________________________________
		</div>
		<div id ="section">
			<h2>rverma@sfu.ca</h2>
			<h2>cyahn@sfu.ca</h2>
			<h2>lza93@sfu.ca</h2>
			<h2>codyc@sfu.ca</h2>
			<h2>minxinz@sfu.ca</h2>
	</div>
	</div>
</div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title,"HOME") %>
<% provide(:content, "This app provides you with a platform for buying/selling SFU books.") %>
<% provide(:name, "Home") %>

<div class = "center jumbotron">
	<h1>Welcome to SFU Used Book Sales</h1> 
	<!--<h2> 
		<%= yield (:name) %> 
	</h2> -->
	<p>
		<%= yield (:content) %>
	</p>

	<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>


<!-- Add Image here -->
<!--<%= link_to image_tag("SFU.jpg", alt: "SFU logo"),
            'http://www.sfu.ca/' %> -->

app/views/static_pages/profile.html.erb
<% if current_user %>

  </br>
  <div class="panel panel-default">
    <div class="panel-body">
      <h1>Profile</h1>
      <ul>
        <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
         <li><strong>Username:</strong> <%= current_user.username %></li>
        <li><strong>Email:</strong> <%= current_user.email %></li>
        <li><strong>Account</strong> Created at <%= current_user.created_at%></li>
        <li><strong>Updated at</strong> <%= current_user.updated_at%></li>
        
        

      </ul>
    </div>
  </div>
<%end%>